[package]
name = "dino-park-fossil"
version = "0.0.3"
authors = ["Florian Merz <flomerz@gmail.com>"]
edition = "2018"

[features]
default = []
localuserscope = ["dino_park_gate/localuserscope"]

[dependencies]
cis_client = { git = "https://github.com/fiji-flo/cis_client-rust", branch = "0.1.6", version = "0.1.6" }
cis_profile = { git = "https://github.com/fiji-flo/cis_profile-rust", branch = "0.1.4", version = "0.1.4", features = ["aws", "vendored"] }
dino_park_gate = { git = "https://github.com/fiji-flo/dino-park-gate", branch = "0.1.1", version = "0.1.1" }
actix-web = { version = "1.0", features = ["ssl"] }
actix-cors = "0.1.0"
actix-multipart = "0.1.1"
futures = "0.1"
log = "0.4"
env_logger = "0.7"
serde = "1.0.80"
serde_json = "1.0.32"
serde_derive = "1.0.80"
reqwest = "0.9.17"
chrono = "0.4.6"
config = "0.9"
rusoto_core = "0.42.0"
rusoto_s3 = "0.42.0"
image = "0.22"
failure = "0.1.5"
failure_derive = "0.1.5"
data-url = "0.1.0"
base64 = "0.11"
sha2 = "0.8"
uuid = { version = "0.8", features = ["v4"] }
lru_time_cache = "0.9.0"
