[package]
name = "dino-park-fossil"
version = "0.0.2"
authors = ["Florian Merz <flomerz@gmail.com>"]
edition = "2018"

[dependencies]
cis_client = { git = "https://github.com/fiji-flo/cis_client-rust", branch = "0.1.2", version = "0.1.2" }
cis_profile = { git = "https://github.com/fiji-flo/cis_profile-rust", branch = "0.1.2", version = "0.1.2" }
dino_park_gate = { git = "https://github.com/fiji-flo/dino-park-gate", branch = "future", version = "0.1.0-beta.3" }
actix-web = { version = "1.0.2", features = ["ssl"] }
actix-cors = "0.1.0"
actix-multipart = "0.1.1"
futures = "0.1"
log = "0.4"
env_logger = "0.6"
serde = "1.0.80"
serde_json = "1.0.32"
serde_derive = "1.0.80"
reqwest = "0.9.17"
chrono = "0.4.6"
config = "0.9"
rusoto_core = "0.40.0"
rusoto_s3 = "0.40.0"
image = "0.22"
failure = "0.1.5"
failure_derive = "0.1.5"
data-url = "0.1.0"
base64 = "0.10"
sha2 = "0.8"
uuid = { version = "0.7", features = ["v4"] }